import { colors } from "styles/theme";
import { loginWithGitHub } from "firebase/client";
import { useEffect } from "react";
import { useRouter } from "next/router";
import AppLyout from "@c/AppLyout";
import Button from "@c/Button";
import GitHub from "@c/Icons/GitHub";
import Head from "next/head";
import Image from "next/image";
import useUser, { USER_STATES } from "hooks/useUser";

export default function Home() {
  const user = useUser();
  const router = useRouter();

  useEffect(() => {
    user && router.replace("/Home");
  }, [user, router]);

  const handleClick = () => {
    loginWithGitHub().catch((err) => {
      console.log(err);
    });
  };

  return (
    <div>
      <Head>
        <title>DevTer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLyout>
        <section>
          <Image src="/Logo.png" alt="Logo" width={"120px"} height={"120px"} />
          <h1>DevTer</h1>
          <h2>
            Talk about development <br /> whit developers 👨‍💻 👩‍💻
          </h2>
          <div>
            {user === USER_STATES.NOT_LOGGED && (
              <Button onClick={handleClick}>
                <GitHub fill="#fff" width={24} height={24} />
                Login with GitHub
              </Button>
            )}
            {user === USER_STATES.NOT_KNOWN && <span>Loading...</span>}
          </div>
        </section>
      </AppLyout>

      <style jsx>
        {`
          section {
            display: grid;
            height: 100%;
            place-content: center;
            place-items: center;
          }

          h1 {
            color: ${colors.primary};
            font-weight: 800;
            margin-botton: 16px;
          }

          h2 {
            color: ${colors.secundary};
            font-size: 21px;
            margin: 0;
          }

          div {
            margin-top: 10px;
          }
        `}
      </style>
    </div>
  );
}
