import { useState, useEffect } from "react";
import Head from "next/head";
import AppLyout from "@c/AppLyout";
import Image from "next/image";
import Button from "@c/Button";
import { colors } from "styles/theme";
import GitHub from "@c/Icons/GitHub";
import { loginWithGitHub, onAuthStateChanged } from "firebase/client";
import Avatar from "@c/Avatar";

export default function Home() {
  const [user, setUser] = useState(null);

  useEffect(() => {
    onAuthStateChanged(setUser);
  }, []);

  const handleClick = () => {
    loginWithGitHub()
      .then((user) => {
        const { avatar, username, url } = user;
        setUser(user);
      })
      .catch((err) => {
        console.log(err);
      });
  };

  return (
    <div>
      <Head>
        <title>DevTer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AppLyout>
        <section>
          <Image src="/Logo.png" alt="Logo" width={"120px"} height={"120px"} />
          <h1>DevTer</h1>
          <h2>
            Talk about development <br /> whit developers 👨‍💻 👩‍💻
          </h2>
          <div>
            {user === null ? (
              <Button onClick={handleClick}>
                <GitHub fill="#FFF" />
                Login with GitHub
              </Button>
            ) : (
              <div>
                <Avatar
                  alt={user.username}
                  src={user.avatar}
                  text={user.username}
                />
              </div>
            )}
          </div>
        </section>
      </AppLyout>

      <style jsx>
        {`
          section {
            display: grid;
            height: 100%;
            place-content: center;
            place-items: center;
          }

          h1 {
            color: ${colors.primary};
            font-weight: 800;
            margin-botton: 16px;
          }

          h2 {
            color: ${colors.secundary};
            font-size: 21px;
            margin: 0;
          }

          div {
            margin-top: 10px;
          }
        `}
      </style>
    </div>
  );
}
